version: '3.1'
services:
  stats-server:
    build: stats/service
    image: ewm-stats-service
    container_name: ewm-stats-service
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stats
      - SPRING_DATASOURCE_USERNAME=java-explore-with-me
      - SPRING_DATASOURCE_PASSWORD=password

  stats-db:
    image: postgres:15.3-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm-stats
      - POSTGRES_USER=java-explore-with-me
      - POSTGRES_PASSWORD=password
      - TZ=Europe/Moscow

# ewm-db:
#    image: postgres:15.3-alpine
#    container_name: ewm-db
#    ports:
#      - "6541:5432"
#    environment:
#      - POSTGRES_DB=ewm-db
#      - POSTGRES_USER=java-explore-with-me
#      - POSTGRES_PASSWORD=password
